### ISSUE TITLE
local-sniffer.cap doesn't work with ICMP packets

### ISSUE THREAD

**Issue by q2dg** [bettercap/caplets#11]
If I run _./bettercap -caplet caplets/local-sniffer.cap_ in one terminal and I run _ping whatever_ in other terminal of same machine (_net.sniff.local_ is set to true), on Bettercap's screen doesn't appear any package.

If I run ping from another machine, doing an arp spoofing to this machine (basically, adding _set arp.spoof.targets ipRemoteMachine ; arp.spoof on_ before _net.sniff on_ line on local-sniffer.cap caplet) does'nt show anything, neither.

**Comment by evilsocket** [comment]
set net.sniff.verbose true

**Comment by q2dg** [comment]
Nop. I've tried and same behaviour. It's only leaked the DNS request before actually the pinging.

**Comment by eenblam** [comment]
```bash
sudo bettercap -caplet caplets/local-sniffer.cap -debug
(...) [sys.log] [dbg] Missing transport layer skipping packet.
```

Got that for every ICMP packet while pinging another host.

Recompiled to `log.Debug(pkt.String())` after the above debug line, and the packet was indeed ICMP.

Working on a fix.

**Comment by eenblam** [comment]
https://github.com/bettercap/bettercap/pull/335#issuecomment-420241592
> ICMP packets were skipped on purpose as they carry no useful info.
