### ISSUE TITLE
http-dump-req caplet doesn't dump nearly anything

### ISSUE THREAD

**Issue by q2dg** [bettercap/caplets#12]
I attach two images, one when using http.proxy and another when using https.proxy. Requests are intercepted (it seems so) but there's nearly no information logged on screen. I've looked at associated Javascript code and, in theory, a lot more data should be shown.

I'm using bettercap 2.4 in Ubuntu 17.10 64 bits, binary downloaded from official releases

With http.proxy:
![http proxy](https://user-images.githubusercontent.com/7274874/38472477-078e564a-3b81-11e8-8a21-e00e6e4eaa16.png)

With https.proxy:
![https proxy](https://user-images.githubusercontent.com/7274874/38472478-07db5e40-3b81-11e8-9e2c-94d95133d6c8.png)

**Comment by yungtravla** [comment]
Can you please write the complete issue? We can't help you if you just dump the result here and expect us to figure out what you're doing.

![screenshot from 2018-04-09 11-58-08](https://user-images.githubusercontent.com/29265684/38475736-5923346e-3bed-11e8-8aaa-fb5cb59a552b.png)

**Comment by q2dg** [comment]
Ok. If I enter into interactive console of Bettercap (version 2.4 installed from official binary release in a VirtualBox VM with a Ubuntu Server 17.10 64 bits OS with its enp0s3 interface in "bridged" mode) and I execute on it these commands (192.168.1.2 is the IP of my real system)...:

_set http.proxy.script caplets/http-req-dump.js
http.proxy on
set arp.spoof.targets 192.168.1.2
arp.spoof on_

...I get first screenshot shown above. If I execute these commands...

_set https.proxy.script caplets/http-req-dump.js
https.proxy on
set arp.spoof.targets 192.168.1.2
arp.spoof on_

..I get second screenshot show above, instead.

Maybe it's an error in VBox network stack, maybe it's an error in Ubuntu's network stack (I use systemd-networkd with netplan disabled)...well, if nobody else has this error, it's fine it remain closed. But it's good having it here as a reference.
Thanks

**Comment by yungtravla** [comment]
Is your only problem that the headers are missing? Traffic is being proxied fine?

**Comment by q2dg** [comment]
Yes!
