### ISSUE TITLE
Install path incompatible with macOS System Integrity Protection

### ISSUE THREAD

**Issue by DominikTo** [bettercap/caplets#25]
`/usr` (with the exception of `/usr/local`) is not writable when SIP is enabled on macOS([1]).
For compatibility with macOS the [Makefile](https://github.com/bettercap/caplets/blob/c6aeaf60ed21e903749e204fa0ec90e81a0d930e/Makefile#L2-L4) should use `/usr/local/bettercap` instead of `/usr/share/bettercap/`.

[1]: https://support.apple.com/en-us/HT204899

**Comment by Arthur111** [comment]
Rather /usr/local/share/bettercap
