### ISSUE TITLE
[Hstshijack.cap] Error when loading hstshijack/hstshijack.cap

### ISSUE THREAD

**Issue by s7x** [bettercap/caplets#29]
Hi!

When I try to use hstshijack.cap, I get an error when bettercap tries to load the hstshijack.js file.
Strangely, it works if I'm modifying the .cap file to include a full path of the js file for the "set http.proxy.script" option.

**Command used to run the tool:**
> sudo bettercap -caplet /usr/local/share/bettercap/caplets/hstshijack/hstshijack.cap

or when including the caplet in a live run

> bettercap
> include /usr/local/share/bettercap/caplets/hstshijack/hstshijack.cap

**Error log:**
> bettercap v2.9 (type 'help' for a list of commands)
> [13:39:13] [sys.log] [inf] loading proxy script hstshijack/hstshijack.js ...
> [13:39:13] [sys.log] [err] Error while running caplet /usr/local/share/bettercap/caplets/hstshijack/hstshijack.cap: open hstshijack/hstshijack.js: no such file or directory

**System:**
Arch Linux 4.18.8.a-1-hardened
Installed via the AUR package [bettercap-git](https://aur.archlinux.org/packages/bettercap-git)

**Bettercap version:**
bettercap v2.9

[EDIT]
Cheers & thanks for this awesome tool.

**Comment by yungtravla** [comment]
Hey, it looks like `~/caplets` and `/usr/local/share/bettercap/caplets` directories are scanned only when loading a caplet (.cap file).
Other methods such as `readFile()` and `set http.proxy.script` require the full path.

I have updated the caplet to make this more apparent :)

**Comment by s7x** [comment]
Wow awesomely fast! Thanks a lot!

**Comment by praveenvishnu17** [comment]
> Hey, it looks like `~/caplets` and `/usr/local/share/bettercap/caplets` directories are scanned only when loading a caplet (.cap file).
> Other methods such as `readFile()` and `set http.proxy.script` require the full path.
> 
> I have updated the caplet to make this more apparent :)

can you please explain in brief and with clear

**Comment by vivek-vijayan** [comment]
I believe you are using Linux OS system, because its directory doesn't have `/usr/local/share` as it is applicable only to MacOS.

Try to change it to `/usr/share` for log, payload & script and then it will work

**Comment by amon1axez** [comment]
> I believe you are using Linux OS system, because its directory doesn't have `/usr/local/share` as it is applicable only to MacOS.
> 
> Try to change it to `/usr/share` for log, payload & script in the **cap** file and then it will work

how so ?
