### ISSUE TITLE
doubt about caplets

### ISSUE THREAD

**Issue by endikap100** [bettercap/caplets#31]
Hi!
I have a doubt that i don't know if its a bug or a feature XD
when you load a caplet like  `bettercap -iface wlan0 -caplet jsinject/jsinject.cap` it gives and import error of `jsinject/jsinject.js`  because it doesn't have the absolute path but when you take the commands that compose that caplet and execute them in the interactive console they work fine.
is it a malfunction? or am i doing something wrong?

**Comment by benleb** [comment]
see https://github.com/bettercap/caplets/issues/29

**Comment by endikap100** [comment]
Thank but it doesn't solve my doubt.
The first example is using `bettercap -iface wlan0 -caplet jsinject/jsinject.cap`.
![imagen](https://user-images.githubusercontent.com/14931821/47031971-70df6b80-d171-11e8-87ce-e6af62dfb391.png)
and the second one is with the interactive console.
![imagen](https://user-images.githubusercontent.com/14931821/47032050-a5ebbe00-d171-11e8-90fe-45956dc72661.png)
in the issue you send me, it says that `set http.proxy.script` require the full path but it works if you are in the correct folder when you use an interactive console but it doesn't work using caplets.

**Comment by yungtravla** [comment]
please set the full path for `http.proxy.script`

**Comment by endikap100** [comment]
ok, thanks
