### ISSUE TITLE
Could not read undefined: open undefined: no such file or directory With full path set

### ISSUE THREAD

**Issue by rsjm** [bettercap/caplets#34]
Hi 

I'm probably missing something obvious , can u guys help me?

Downloaded Caplets to /usr/local/share/bettercap/caplets/ and updated

Running bettercap from ~   

![screenshot from 2018-11-18 13-36-09](https://user-images.githubusercontent.com/45144422/48673237-477e7a80-eb37-11e8-8985-e07441fee84f.png)

**Comment by yungtravla** [comment]
thanks!
