### ISSUE TITLE
Facebook/gmail account

### ISSUE THREAD

**Issue by user568989** [bettercap/caplets#39]
Before i even start to use the new version of bettercap ( was dealing with other stuff ) i want to know everything about this tool and generally to know about SSL and prealoded hsts sites...
From what i see with the new caplets that can be stored in bettercap and u can use them to inject a fake facebook/gmail site that's the victim visit to grab his password is that right?
Or it still can't be done with these websites like gmail and facebook cause they always look for https and never start facebook/gmail if the page is starting wjth http (preloaded hsts) 
Can u explain me more about how this work?
There is no way that stealing password from gmail/facebook is impossible....

**Comment by yungtravla** [comment]
Welcome to bettercap.

The manual is [here](https://github.com/bettercap/caplets/wiki).

You can learn how HTTP, TLS and HSTS works [here](https://www.google.com/).

**Comment by user568989** [comment]
The "here" represents google ... lol :)

**Comment by yungtravla** [comment]
@user568989 exactly :)
