### ISSUE TITLE
Where is documentation on what a certain caplet does?

### ISSUE THREAD

**Issue by gmelodie** [bettercap/caplets#49]
There are some caplets that don't have a `README` file on them and, in most of those who do, there is almost no information regarding what that caplet does. If this is intentional, why aren't there any links pointing directly to the more detailed documentation on each caplet? I've read the  official Bettercap documentation (which I didn't find of much help) but there is no mention to each caplet specifically.

Is there need for documentation improvement or I'm just looking in the wrong places? 

**Obs.:** For the sake of completeness take as an example the RTFM module. There is no `README` and the name is an acronym :cry:

**Comment by yungtravla** [comment]
You can open the javascript file and see what it does.
