### ISSUE TITLE
caplets.update doesn't work on Kali Linux

### ISSUE THREAD

**Issue by DarkSkull91** [bettercap/caplets#60]
I installed bettercap-caplets with command:
`sudo apt install bettercap-caplets`
but when I run in bettercap `caplets.update` I got this error:
`192.168.1.0/24 > 192.168.1.2  » [22:46:27] [sys.log] [inf] caplets this command is inactive in Kali. Install the Kali package bettercap-caplets to get the caplets`

Kali has installed caplets in `/usr/share/bettercap/caplets/`, is the right path?

**Comment by Lordjoel28** [comment]
To install / update the caplets on your computer:
git clone https://github.com/bettercap/caplets.git
cd caplets
sudo make install

**Comment by karpiyon** [comment]
Hi, 
I am also having difficulties in updating Bettercap caplets on Kali,
I run `sudo make install`, however I cannot see any changes under:
`/usr/share/bettercap/caplets
`
Is this the directory the caplet should be installed to?
Can i simply copy the caplet folders to this one manually?

**Comment by karpiyon** [comment]
I noticed that in the MakeFile it creates:
`/usr/share/bettercap/caplets` my bettercap shared are under:
`/usr/**local**/share/bettercap/caplets`

**Comment by DghostNinja** [comment]
Close bettercap if it's running and enter “sudo apt-get install bettercap-caplets”. Once installation is done, run better cap and check the “caplets.show” all over again, you should see your caplets now.

**Comment by Marvicho18** [comment]
I have an issue with this topic also. When I use caplets.update show a message: "caplets this cmd is inactive in Kali. Install the kali pckg better-caplets to get the caplets. I follow every step and I already download the caplets with apt-get install bettercap-caplets.

Using bettercap when I use caplets.show I can see all the caplets in list, but when I use caplets.update shows again the error:  "caplets this cmd is inactive in Kali. Install the kali pckg better-caplets to get the caplets"

**Comment by TerAondona** [comment]
> I have an issue with this topic also. When I use caplets.update show a message: "caplets this cmd is inactive in Kali. Install the kali pckg better-caplets to get the caplets. I follow every step and I already download the caplets with apt-get install bettercap-caplets.
> 
> Using bettercap when I use caplets.show I can see all the caplets in list, but when I use caplets.update shows again the error: "caplets this cmd is inactive in Kali. Install the kali pckg better-caplets to get the caplets"


solution

use: https://github.com/bettercap/caplets.git
if it shows you error with a link open the link and copy the proper link and paste it in terminal and run, it should work as it worked for me
