### ISSUE TITLE
HTTPS downgrade not working at all.

### ISSUE THREAD

**Issue by parikshitlfj12** [bettercap/caplets#63]
HSTShijack caplet isn't downgrading the HTTPS secured websites to HTTP. 
Need help.

**Comment by buffermet** [comment]
Nowhere has anyone ever stated that hstshijack downgrades HTTPS connections. It can spoof them if a HTTP request is intercepted.

Downgrading an already established HTTPS connection is simply not possible.

You should seriously do some reading on both bettercap, hstshijack, SSL and HSTS before posting issues.
