### ISSUE TITLE
I can not able to remove bettercap caplets

### ISSUE THREAD

**Issue by Deepak57-del** [bettercap/caplets#66]
![Kali-Linux-2020 4-vbox-amd64  Running  - Oracle VM VirtualBox 24-01-2021 12 49 18 PM_LI](https://user-images.githubusercontent.com/72692812/105623827-e3584f00-5e42-11eb-92f9-3515bca24b54.jpg)

**Comment by buffermet** [comment]
Because you're not root.

`sudo rm /usr/share/bettercap/caplets/hstshijack`
