### ISSUE TITLE
I keep getting the error when running hstshijack/hstshijack in bettercap

### ISSUE THREAD

**Issue by jsarkari** [bettercap/caplets#67]
I keep getting the error when running hstshijack/hstshijack in bettercap

10.0.2.0/24 > 10.0.2.15  » [12:52:49] [sys.log] [err] type error Cannot access member 'to Lower Case' of undefined
10.0.2.0/24 > 10.0.2.15  » hstshijack/hstshijack
2021-08-09 12:58:59 inf hstshijack Generating random variable names for this session 
2021-08-09 12:58:59 inf hstshijack Reading caplet 
10.0.2.0/24 > 10.0.2.15  » [12:58:59] [sys.log] [err] Error while executing on Load call back:
Traceback:
  Type Error: Cannot access member 'to Lower Case' of undefined
    at configure (<anonymous>:474:21)
    at on Load (<anonymous>:593:3)

**Comment by rtr989** [comment]
Caplet:
set hstshijack.log             /usr/local/share/bettercap/caplets/hstshijack/ssl.log
set hstshijack.payload         /usr/local/share/bettercap/caplets/hstshijack/payloads/hstshijack-payload.js
set hstshijack.ignore          *
set hstshijack.targets       *.com,*.net,*.co.uk
set hstshijack.replacements  *.corn,*.nel,*.cc.uk
set hstshijack.obfuscate       true
set hstshijack.encode          false
set hstshijack.payloads        *:/usr/local/share/bettercap/caplets/hstshijack/payloads/hijack.js,*:/usr/local/share/bettercap/caplets/hstshijack/payloads/sslstrip.js,*:/usr/local/share/bettercap/caplets/hstshijack/payloads/keylogger.js

set http.proxy.script     /usr/local/share/bettercap/caplets/hstshijack/hstshijack.js
set http.proxy.port       8080
set dns.spoof.domains     *.corn,*.nel,*.cc.uk

dns.spoof     on
net.sniff     on
http.proxy    on


result:

2022-07-22 11:34:52 inf hstshijack Generating random variable names for this session ...
2022-07-22 11:34:52 inf hstshijack Reading caplet ...
[11:34:52] [sys.log] [err] Error while executing onLoad callback:
Traceback:
  TypeError: Cannot access member 'toLowerCase' of undefined
    at configure (<anonymous>:474:21)
    at onLoad (<anonymous>:593:3)

└─# bettercap -version
bettercap v2.32.0 (built for linux amd64 with go1.18.1)

**Comment by buffermet** [comment]
Update your caplets.

**Comment by rtr989** [comment]
caplets downloaded today from https://github.com/bettercap/caplets.git

**Comment by buffermet** [comment]
Yet you are running an old config.

Do `caplets.update` in bettercap, you're not loading the latest one.

Also you need to provide all the commands, not just the caplet code. I don't want to have to guess what you are doing.

**Comment by 0mba3** [comment]
when I type in (( bettercap ))
hstshijack/hstshijack  
it response >> [06:38:24] [sys.log] [err] open /usr/local/share/bettercap/caplets/hstshijack/hstshijack.js: no such file or directory
——
who I can fix this

**Comment by Mxlkommarz** [comment]
hi 
i am having the same issue while using bettercap this is the error that is displayed when i try to use hshshijack i also did caplets.update in bettecap but still the same result how do i resolve this issue thanks 

192.168.8.0/24 > 192.168.8.103  » hstshijack/hstshijack
2024-08-08 05:20:22 inf hstshijack Generating random variable names for this session ...
2024-08-08 05:20:22 inf hstshijack Reading caplet ...
192.168.8.0/24 > 192.168.8.103  » [05:20:22] [sys.log] [err] Error while executing onLoad callback: 
Traceback:
  TypeError: Cannot access member 'toLowerCase' of undefined
    at configure (<anonymous>:498:21)
    at onLoad (<anonymous>:623:3)

192.168.8.0/24 > 192.168.8.103  » [05:20:22] [sys.log] [err] TypeError: Cannot access member 'toLowerCase' of undefined
